name: CI Pipeline - Client

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/*client*.yaml'

  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/*client*.yaml'

concurrency:
  group: CI-client
  cancel-in-progress: true

env:
  fail-on-lint: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Run npm CI
        id: ci
        working-directory: client
        run: npm ci

      - name: Error if npm CI fails
        if: always() && steps.ci.outcome == 'failure'
        run: echo "::error::An error occurred during npm ci on the client module. Please inspect package.json and/or delete package-lock.json and recreate it!" && exit 1

      - name: Lint
        id: lint
        working-directory: client
        continue-on-error: ${{ env.fail-on-lint == 'false' }}
        run: npm run lint

      - name: Warn if Lint fails
        if: always() && steps.lint.outcome == 'failure'
        run: echo "::warning::Linting failed on the client module. Please inspect the workflow logs for more information."

      - name: Build
        working-directory: client
        run: npm run build