name: CI Pipeline - Server

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/*server*.yaml'

  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/*server*.yaml'

concurrency:
  group: CI-server
  cancel-in-progress: true

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Run npm CI
        id: ci
        working-directory: server
        run: npm ci

      - name: Error if npm CI fails
        if: always() && steps.ci.outcome == 'failure'
        run: echo "::error::An error occurred during npm ci on the server module. Please inspect package.json and/or delete package-lock.json and recreate it!" && exit 1

      - name: Build
        working-directory: server
        run: npm run build

      - name: Upload Dist as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist